version: "3"

services: 
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on: 
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  redis-init:
    image: redis:alpine
    command: "sh /data/init.sh"
    volumes:
      - ./initial_data/redis:/data
    depends_on:
      - redis
    env_file:
      - .env
  client-web:
    build:
      context: ./client-web
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro