name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for remote-job-finder-api
        id: meta_api
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: turgaysozen/remote-job-finder-api

      - name: Build and push Docker image for remote-job-finder-api
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}

      - name: Extract metadata (tags, labels) for remote-job-finder-client-web
        id: meta_client_web
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: turgaysozen/remote-job-finder-client-web

      - name: Build and push Docker image for remote-job-finder-client-web
        run: |
          docker build ./client-web \
            --file ./client-web/Dockerfile.client \
            --tag turgaysozen/remote-job-finder-client-web \
            --build-arg NEXT_PUBLIC_API_ENDPOINT=http://3.72.248.113:8080
          docker push turgaysozen/remote-job-finder-client-web

      - name: Extract metadata (tags, labels) for redis-init
        id: meta_redis_init
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: turgaysozen/redis-init

      - name: Build and push Docker image for redis-init
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_redis_init.outputs.tags }}
          labels: ${{ steps.meta_redis_init.outputs.labels }}

      - name: Deploy to VPS
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          ssh -i $VPS_SSH_KEY ubuntu@3.72.248.113 "docker-compose pull && docker-compose up -d"