name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check git diff for remote-job-finder-api
        id: remote-job-finder-api
        run: |
          if git diff --quiet HEAD^ HEAD -- . ':!client-web' ':!.github' ':!README.md'; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi

      - name: Extract metadata (tags, labels) for remote-job-finder-api
        if: steps.remote-job-finder-api.outputs.changed == 'true'
        id: meta_api
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: turgaysozen/remote-job-finder-api

      - name: Build and push remote-job-finder-api image
        if: steps.remote-job-finder-api.outputs.changed == 'true'
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}

      - name: Check git diff for remote-job-finder-client-web
        id: remote-job-finder-client-web
        run: |
          if git diff --quiet HEAD^ HEAD -- client-web; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi

      - name: Extract metadata (tags, labels) for remote-job-finder-client-web
        if: steps.remote-job-finder-client-web.outputs.changed == 'true'
        id: meta_client_web
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: turgaysozen/remote-job-finder-client-web

      - name: Build and push remote-job-finder-client-web image
        if: steps.remote-job-finder-client-web.outputs.changed == 'true'
        run: |
          docker build ./client-web \
            --file ./client-web/Dockerfile.client \
            --tag turgaysozen/remote-job-finder-client-web \
            --build-arg NEXT_PUBLIC_API_ENDPOINT=http://3.72.248.113:8080
          docker push turgaysozen/remote-job-finder-client-web

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 3.72.248.113 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.72.248.113 \
          "sudo su -c '
          cd /home/ubuntu/go-web &&
          docker-compose pull &&
          docker-compose down &&
          docker-compose up -d'"